import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Sidebar } from '../components/SideBar';
import { TaskBoard } from '../components/TaskBoard';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Task management app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TaskBoard title="asdasd" />
    </div>
  );
};

export default Home;
