import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Toaster } from 'react-hot-toast';
import { TaskBoard } from '../components/TaskBoard';

const Home: NextPage = () => {
  const [showToaster, setShowToaster] = useState<boolean | undefined>();
  useEffect(() => {
    if (showToaster === undefined) {
      setShowToaster(true);
    }
  }, [showToaster]);
  return (
    <div>
      <Head>
        <title>Task management app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {showToaster && <Toaster />}
      <TaskBoard />
    </div>
  );
};

export default Home;
