import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Sidebar } from '../components/SideBar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Task management app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>This be working</h1>
    </div>
  );
};

export default Home;
